import React from 'react';
import Carousel from 'react-bootstrap/Carousel'
import img1 from "../images/instructor-bg.png"
import img2 from "../images/sampleimg.png"
import img3 from "../images/try.png"
import img4 from "../images/try2.png"
import "../stylesheets/Login.css"
class FrontCarousel extends React.Component{
    render()
    {
       
        return(
            
                <Carousel>
                <Carousel.Item interval={1000}>
                    <center>
                    <img
                    // class="d-block w-100"
                    src={img4}
                    width={500}
                    height={500}
                    alt="First slide"
                    thumbnail
                    />
                    </center>
                    <br/><br/><br/>
                    <Carousel.Caption>
                    <h3>Virtual Learning Platform</h3>
                    <p>View content generated by instructors at your leisure.</p>
                    </Carousel.Caption>
                </Carousel.Item>
                <Carousel.Item interval={1000}>
                    <center>
                    <img
                    //class="d-block w-100"
                    width={500}
                    height={300}
                    src={img3}
                    alt="Second slide"
                    thumbnail
                    />
                    </center>
                    <br/><br/><br/>
                    <Carousel.Caption>
                    <h3>Welcome</h3>
                    <p>Doctrina is a Virtual Learning Platform that facilitates Flipped Mode of Instruction..</p>
                    </Carousel.Caption>
                </Carousel.Item>
                {/* <Carousel.Item>
                    <center>
                    <img
                    src={img1}
                    width={500}
                    height={500}
                    alt="Third slide"
                    thumbnail
                    />
                    </center>
                    <Carousel.Caption>
                    <h3>Third slide label</h3>
                    <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                    </Carousel.Caption>
                </Carousel.Item> */}
                </Carousel>
            
        )
    }
}

export default FrontCarousel;